//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_FV1_
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasesToValidation
    {
        public int CaseToValidationId { get; set; }
        public Nullable<int> CaseId { get; set; }
        public Nullable<int> ValidationId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual TestCas TestCas { get; set; }
        public virtual Validation Validation { get; set; }
    }
}
