//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_FV1_
{
    using System;
    using System.Collections.Generic;
    
    public partial class StepsToStepParameter
    {
        public int StepsToStepParameters { get; set; }
        public Nullable<int> StepId { get; set; }
        public Nullable<int> StepParameterId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual StepParameter StepParameter { get; set; }
        public virtual Step Step { get; set; }
    }
}
