//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_FV1_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToAction
    {
        public int ToActionId { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<int> ActionId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Step Step { get; set; }
        public virtual Validation Validation { get; set; }
    }
}
