//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject_FV1_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidationParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ValidationParameter()
        {
            this.ValidationsToValidationParameters = new HashSet<ValidationsToValidationParameter>();
        }
    
        public int ValidationParameterId { get; set; }
        public string Name { get; set; }
        public string value { get; set; }
        public Nullable<int> Type { get; set; }
        public string SqlExpression { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ValidationsToValidationParameter> ValidationsToValidationParameters { get; set; }
    }
}
