//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCas
    {
        public int CaseId { get; set; }
        public string Scenario { get; set; }
        public Nullable<int> SectionId { get; set; }
        public int SuitId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Suit Suit { get; set; }
    }
}
